apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    #get
    p, role:readonly, applications, get, */*, allow
    #FOR DEVLEADS
    #sync access to all the project whose name prefix is project- : includes project x, x-platform and project-y
    p, role:devlead, applications, sync, project-*/*, allow
    
    #deployment restart only for project-x and project-x-platform
    p, role:devlead, applications, action/apps/Deployment/restart, project-x/*, allow
    p, role:devlead, applications, action/apps/Deployment/restart, project-x-*/*, allow
    
    #application delete only for project-x and project-x-platform
    p, role:devlead, applications, delete, project-x/*, allow
    p, role:devlead, applications, delete, project-x-*/*, allow


    #scale permission for DEVLEADS
    p, role:devlead, applications, action/apps/Deployment/scale, project-*/*, allow

    #FOR DEVELOPERS
    #Only Sync access to only projects x and y and not the x-platform
    p, role:developer, applications, sync, project-x/*, allow
    p, role:developer, applications, sync, project-y/*, allow
    
    #for all other people who have no roles or role:none
    p, role:none, *, *, *, deny

    # Assignments
    g, developer, role:readonly
    g, devlead, role:readonly
    g, platformlead, role:readonly
    g, developer, role:developer
    g, devlead, role:devlead
    g, platformlead, role:devlead
  policy.default: role:none