apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-x
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: project X for holiding project X related applications
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: project-x
  source:
    path: development
    repoURL: https://github.com/aniruddha-sinha/argo-cd-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
